### ISSUE TITLE
Mapping of empty string values

### ISSUE THREAD

**Issue by richarth** [AndyButland/UmbracoMapper#11]
If you have a property with no value that is being mapped to a string property, then since 2.0.5 the model you will end up with a null value rather than the empty string you used to get in 2.0.4.

I wondered what thoughts are on this behaviour.  Personally if my property doesn't have a value then I'd rather have an empty string than null.

**Comment by AndyButland** [comment]
Just reviewing, can see this small behaviour change has crept in between those versions, which came about due to another amend to ensure default values are respected.  With that change, I did have to then make sure a value existed on the content item before setting it, otherwise the default would get overwritten.  You can see the relevant commit [here](https://github.com/AndyButland/UmbracoMapper/commit/2c299a2fb139d864ff5b34ff4c2239032cbbbd76).

I think it's probably OK though.  If there's no value then arguably null is more appropriate than empty string, though I take the point you might prefer the latter on the view model (think I would too).  In that case though you could set the property to empty string in the view models constructor, or use the new C# syntax of `public string MyString { get; set; } = string.Empty`

**Comment by richarth** [comment]
Thanks for reviewing this.  I've gone with the new C# syntax, it just meant adding this in a lot of places.

**Comment by AndyButland** [comment]
Going to close this off... been a while and workaround exists.
