### ISSUE TITLE
Nested content (IPublishedElement)

### ISSUE THREAD

**Issue by shearer3000** [AndyButland/UmbracoMapper#18]
Hello
In umbraco 8, Nested content becomes IPublishedElement (not IPublishedContent). Is there support for mapping this interface in UmbracoMapper?
thanks
Andrew

**Comment by AndyButland** [comment]
Hi Andrew - it's a good point, I've not considered this.  Will have a look to see how feasible it is to add.

**Comment by AndyButland** [comment]
Think I've got this working - do you think you'd be up for testing it out to see that it does from your perspective too please?  I've compiled the debug dlls [here](https://www.dropbox.com/s/sk6f3plkmljjzr1/Zone.UmbracoMapper.zip?dl=0) that you can swap into your local project.

You should find you have a `Map` and `MapCollection` method available with the same signatures as the existing ones, except expecting `IPublishedElement` instead of `IPublishedContent`.  You should also find that a view model collection will "automap" from nested content items too.

Work is in `feature/map-nested-content` - which I'll merge in and create a release shortly (ideally after you've confirmed it works as you expect).  Thanks.

**Comment by shearer3000** [comment]
hi Andy 

thanks for looking into this. I've tried the debug dlls in my project and can see the overloads on .Map for IPublishedContent and IPublishedElement now :)

However, I also notice my AddCustomMapping definitions expect the CustomMapping method to be IPublishedElement instead of IPublishedContent. Does AddCustomMapping also need 2 signatures?

thanks
Andrew

**Comment by AndyButland** [comment]
Yes, forgot to mention that - I was thinking having the two signatures (and then the two different defintions of the `CustomMapping` delegates) would get a bit messy (both for use, and for the code internally).  So instead have changed the method signature as you say to accept `IPublishedElement`,

For many custom mappers that change may be all that's needed - i.e. if you are using property values.

In other case, if the method has used some properties of `IPublishedContent` that aren't on `IPublishedElement`, they wouldn't be accessible.  But you could still attempt to case the provided `content` parameter to `IPublishedContent`, and, if that's what you've got, use it's properties.

E.g.

```
            var publishedContent = contentToMapFrom as IPublishedContent;
            if (publishedContent != null)
            {
                // Can now use e.g. publishedContent.Name;
            }
```

Does that sound like it'll work?  Keen to hear from people using it outside of my uses (which currently isn't anything directly on a project, so want to make sure I'm not missing anything).

**Comment by shearer3000** [comment]
Ahh yes, the type check is a workable solution. thanks for the tip.
Personally i wouldn't see having both signatures in UmbracoMapper as messy, but as you say, see what other people think about it. Otherwise, yes this work has been tested in my project and would be great in the next release.
thanks again!

**Comment by AndyButland** [comment]
I've pushed this up in the latest release, 4.2.0, available on our and NuGet.  Thanks for the nudge on getting this feature added.

**Comment by shearer3000** [comment]
thanks again. new 4.2 release working well 👍
