### ISSUE TITLE
Recursive mapping in umbraco 8

### ISSUE THREAD

**Issue by shearer3000** [AndyButland/UmbracoMapper#21]
Hi there

I have a property on my homepage node that I would like the viewmodel of all subpages to automatically inherit.
In umbraco 7 (umbraco mapper 2.x) I used “[PropertyMapping(MapRecursively = true)]” to walk up the content tree to obtain this property.

This doesn’t seem to work in umbraco 8 (umbraco mapper 4.2.1). I also tried this from the readme:
[PropertyMapping(FallbackMethods = new[] { Fallback.Ancestors })]

Should that be the correct decoration?

Thanks

**Comment by shearer3000** [comment]
I also notice that if i map my homepage property using "[PropertyMapping(FallbackMethods = new[] { Fallback.Ancestors })]" and that field is in fact empty then the following is thrown:
`Fallback PublishedValueFallback does not support fallback code '3' at element level.`

**Comment by AndyButland** [comment]
Either should work, and I can see the issue - I've introduced this when implementing mapping from `IPublishedElement`, but elements can't have ancestor fallbacks.  So think I just need to cast it to `IPublishedContent` before getting the property value.

I've committed the fix for this.  Would you mind just checking it on your installation for me too please?  You can download the changes dll [here](https://www.dropbox.com/s/vrhhx1c4cefecdr/Zone.UmbracoMapper.V8.zip?dl=0).  Thanks.

I'll push out a release if it looks good to you.

**Comment by shearer3000** [comment]
hi @AndyButland - Yes that looks pretty good to me - i can see my recursive mapping working now :)
thanks for fixing that

**Comment by AndyButland** [comment]
OK, thanks for checking.  Have pushed that out in release 4.2.2 (on nuget and our).
